global:
  externalUrl: http://test.com
  rollingUpdate:
    maxUnavailable: 1
  noDbAuth: true
  useCloudSql: false
  useCombinedDb: true
  enablePriorityClass: false
  defaultContactEmail: "test@test.com"
  enableMultiTenants: false

tags:
  all: true
  correspondence-api: false
  minion-broken-link: true
  minion-linked-data-rating: true
  minion-visualization: true
  minion-format: true

gateway:
  ckanRedirectionPath: ""
  enableCkanRedirection: false
  enableAuthEndpoint: true
  cors:
    origin: true
  auth:
    facebookClientId: "173073926555600"
    arcgisClientId: "d0MgVUbbg5Z6vmWo"
    googleClientId: "275237095477-f7ej2gsvbl2alb8bcqcn7r5jk0ur719p.apps.googleusercontent.com"
    ckanAuthenticationUrl: https://data.gov.au/data

registry-api:
  skipAuthorization: false
  
web-server:
  fallbackUrl: "https://data.gov.au"
  featureFlags:
    cataloguing: true
#  vocabularyApiEndpoints: 
#    - "https://vocabs.ands.org.au/repository/api/lda/abares/australian-land-use-and-management-classification/version-8/concept.json"
#    - "https://vocabs.ands.org.au/repository/api/lda/neii/australian-landscape-water-balance/version-1/concept.json"
#    - "https://vocabs.ands.org.au/repository/api/lda/ands-nc/controlled-vocabulary-for-resource-type-genres/version-1-1/concept.json"

connectors:
  includeCronJobs: false
  config:
    - image:
        name: "magda-ckan-connector"
      id: dga
      name: "data.gov.au"
      sourceUrl: "https://data.gov.au/"
      pageSize: 1000
      schedule: "0 * * * *"
      ignoreHarvestSources: ["*"]
