apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-volume
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /etc/kubernetes
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            # If using version < 19, change value from docker-desktop to docker-for-desktop.
          - docker-desktop
